version: "3"
services:
  node:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis:alpine
    volumes:
      - ~/volumes/redis:/data
    ports:
      - 6379:6379
  mongodb:
    image: mongo:latest
    volumes:
      - ~/volumes/mongodb:/data/db
    ports:
      - 27017:27017

networks:
  default:
    driver: bridge
